# Generated by Django 4.1.7 on 2023-03-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_delete_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
