# Generated by Django 4.1.7 on 2023-03-13 09:01

import applications.account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', applications.account.models.UserManager()),
            ],
        ),
    ]
